version: "3.3"


networks:
  db-tier:
    driver: bridge
  app-tier:
    driver: bridge  

# volumes:
#   redis_data:
#     driver: local
#   postgresql_data:
#     driver: local
#   mongodb_data:
#     driver: local    

services:
  mana-frontend: 
    container_name: mana-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    
  dpc-dm-api:
    container_name: dpc-dm-api
    image: digieye/dpc-dm-api-prod:d069184
    restart: always
    networks:
      - db-tier
      - app-tier
    ports:
      - 3000:3000
    environment:
      - POSTGRESQL_USERNAME=digieye
      - POSTGRESQL_PASSWORD=cGFzc3dvcmQxMjMK
      - POSTGRESQL_DATABASE=digieye
      - POSTGRESQL_POSTGRES_PASSWORD=Y0dGemMzZHZjbVF4TWpNSwo
      - DATABASE_URL=postgresql://digieye:cGFzc3dvcmQxMjMK@postgresql:5432/digieye?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - JWT_SECRET_KEY=zDHcGFzc3dvcmQxMjMKZjWpNSwo
      -	ACCESS_TOKEN_EXPIRATION_TIME=1200
      - PORT=3000
      - REFRESH_TOKEN_EXPIRATION_TIME=86400
      - NODE_ENV=production

  mana-mqtt-consumer:
    container_name: mana-mqtt-consumer
    image: digieye/mana-mqtt-consumer-prod:fad9a03
    restart: always
    networks:
      - db-tier
      - app-tier
    ports:
      - 4000:4000
      - 4001:4001
    environment:      

      - MONGODB_DATABASE_URL=mongodb://digieye:cGFzc3dvcmQxMjMK@mongodb:27017/digieye?authSource=digieye
      - POSTGRES_DATABASE_URL=postgresql://digieye:cGFzc3dvcmQxMjMK@postgresql:5432/digieye?schema=public
      - PORT=4000
      - SOCKET_PORT=4001
      - NODE_ENV=production
      - MQTT_PORT=1883
      - MQTT_BROKER=mqtt://vernemq
      - SERIALS=[""]
         
  vernemq:
    image: erlio/docker-vernemq
    container_name: vernemq
    restart: always
    networks:
      - db-tier
      - app-tier
    environment:
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'on'
      DOCKER_VERNEMQ_ACCEPT_EULA: 'yes'
    ports:
      - 1883:1883
      - 8888:8888
        
  postgresql: 
    container_name: postgresql
    image: bitnami/postgresql:16.3.0-debian-12-r19
    restart: always
    networks:
      - db-tier
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=digieye
      - POSTGRESQL_PASSWORD=cGFzc3dvcmQxMjMK
      - POSTGRESQL_DATABASE=digieye
      - POSTGRESQL_POSTGRES_PASSWORD=Y0dGemMzZHZjbVF4TWpNSwo
    # volumes:
    #   - 'postgresql_data:/bitnami/postgresql' 
      
  redis:
    image: bitnami/redis:7.0.15-debian-12-r18
    container_name: redis
    restart: always
    networks:
      - db-tier
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    # volumes:
    #   - 'redis_data:/bitnami/redis/data'
  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:7.0.12-debian-12-r2
    restart: always
    networks:
      - db-tier
    ports:
      - 27017:27017
    environment:
      - MONGODB_ROOT_PASSWORD=vcmQbVF4TW3dvcmQpNSwo
      - MONGODB_USERNAME=digieye
      - MONGODB_PASSWORD=cGFzc3dvcmQxMjMK
      - MONGODB_DATABASE=digieye
    # volumes:
    #   - 'mongodb_data:/bitnami/mongodb'  
